### ISSUE TITLE
Дополнить базу данных

### ISSUE THREAD

**Issue by dstsimokha** [dstsimokha/nauchruk#4]
- преподавателей? (с карточками)

**Comment by eylonlina** [comment]
Думаю, здесь нужно просто создать базу данных по нескольким преподавателями нескольким студентам (тк делаем прототип пока только)

**Comment by eylonlina** [comment]
То есть для этого ишью нужно пописать в вики, скажем, по 20 "профилей" для студентов и для преподавателей с определенными параметрами(пол, возраст..... то что ты @dstsimokha  прописывал в описании данных) , чтобы потом по этим "профилям" прописать код и создать 2 базы данных, там где все эти пункты и будут прописаны
